shellchecked

diff --git a/han-rooster-naar-ics b/han-rooster-naar-ics
--- a/han-rooster-naar-ics
+++ b/han-rooster-naar-ics
@@ -25,6 +25,12 @@
 ## Source and documentation:
 ##  https://github.com/ronalde/han-rooster-naar-ics
 
+## shellcheck exceptions
+# shellcheck disable=SC2086
+# shellcheck disable=SC2116
+# shellcheck disable=SC2181
+# shellcheck disable=SC1090
+
 app_name="untis2ics"
 app_info_url="https://github.com/ronalde/han-rooster-naar-ics"
 
@@ -71,6 +77,8 @@ OPTIONAL ARGUMENTS
  -c|--courses-csv-path PATH	   Path to the csv file containing
        information on courses. Defaults to \`${default_courses_csv_filename}' in current
        directory.
+ --temp-storage-dir PATH	   PATH to the directory containing (old and) temporary 
+       ics snippets. 
  --ics-organizer-email ADDRESS	   Sets the MAILTO organizer field to ADDRESS in the ics.
  --ics-organizer-cn COMMON_NAME	   Sets the CN organizer field to COMMON_NAME in the ics.
  --ics-organizer-sentby-email ADDRESS 
@@ -253,6 +261,15 @@ function analyze_command_line() {
                     continue
 		fi
 		;;	    
+            --temp-storage-dir)
+		if [[ "${2}x" == "x" ]]; then
+		    die "argument \`$1' requires a valid PATH."
+		else
+		    arg_temp_storage_dir="$2"
+		    shift 2
+                    continue
+		fi
+		;;	    
             -wo|--overwrite-output)
 		arg_overwrite_output=True
 		shift
@@ -280,9 +297,9 @@ function analyze_command_line() {
 		break
         esac
     done
-    if [[ "$@x" != "x" ]]; then
+    if [[ "$*x" != "x" ]]; then
 	## settings file specified
-	arg_settings_file="$@"
+	arg_settings_file="$*"
     fi
 }
 
@@ -306,7 +323,7 @@ function array_from_csv() {
     match_re="${match_re}[${sep}]*"
     if [[ ! -f "${csvfile}" ]]; then
 	printf 1>&2 "warning in %s: no %s csv file found in \`%s'.\n" \
-		    "${FUNCNAME}" "${datatype}" "${csvfile}"
+		    "${FUNCNAME[0]}" "${datatype}" "${csvfile}"
 	return 1
     else
 	printf 1>&2 "%3s- getting %s from %s ..." \
@@ -325,7 +342,7 @@ function array_from_csv() {
 		    labels_courses["${course_shortcut}"]="${course_fullname}"
 		else
 		    printf 1>&2 "warning in %s: malformed line in csv file \`%s' using match_re \`%s':\n%s\n" \
-				"${FUNCNAME}" "${csvfile}" "${match_re}" "${line}"
+				"${FUNCNAME[0]}" "${csvfile}" "${match_re}" "${line}"
 		    continue
 		fi
 	    done< "${csvfile}"
@@ -354,13 +371,12 @@ function array_from_csv() {
 		    labels_teachers["${teacher_shortcut}"]="${teacher_fullname} ${teacher_details}"
 		else
 		    printf 1>&2 "warning in %s: malformed line in %s csv file \`%s' using match_re \`%s':\n%s\n" \
-				"${FUNCNAME}" "${type}" "${csvfile}" "${match_re}" "${line}"
+				"${FUNCNAME[0]}" "${datatype}" "${csvfile}" "${match_re}" "${line}"
 		    continue
 		fi
 	    done< "${csvfile}"
 	    if [[ ${#labels_teachers[@]} -lt 1 ]]; then
-		printf 1>&2 "errors encountered.\nno teachers found.\n" \
-			    "${FUNCNAME}" "${csvfile}"
+		printf 1>&2 "errors encountered.\nno teachers found.\n"
 		return 1
 	    else
 		printf 1>&2 "done.\n%5s(%d teachers found)\n" \
@@ -381,8 +397,6 @@ function ret_vevent_summary() {
     else
 	course_label="${course}"
     fi
-    teacher="$2"
-    room="$3"
     printf "%s" "${course_label}"
 }
 
@@ -416,11 +430,8 @@ function ret_vevent_dtend() {
     ## return the value for a DTEND line for a VEVENT
     lesson_date="$1"
     starttime="$2"
-    starttime_sec=$(date -d "${starttime}" +"%s")
     endtime_formatted="$(date -d "${starttime} sec + \
 ${lessonduration_minutes} min - 1 sec" +"${ics_dt_timeformat}")"
-    #printf 1>&2  "dtend  : lesson_date=\`%s'\tstarttime=\`%s'\tendtime=\`%s'\n" \
-    #	   "${lesson_date}" "${starttime}" "${endtime_formatted}"
 
     printf "TZID=%s:%s%s" \
 	   "${ics_dt_timezoneid}" "${lesson_date}" "${endtime_formatted}"
@@ -449,7 +460,7 @@ function ret_vevent_attendeechair() {
     else
 	printf 1>&2 "\n%s: teacher abbreviation \`%s' not found in teachers csv file %s;\n \
 consider adding it using:\n%s\n" \
-		    "${FUNCNAME}" "${teacher_field_value}" "${csv_paths["teachers"]}" "${people_lookup_url_base}"
+		    "${FUNCNAME[0]}" "${teacher_field_value}" "${csv_paths["teachers"]}" "${people_lookup_url_base}"
 	return 1
     fi
 
@@ -489,7 +500,7 @@ function ret_vevent_location() {
 	fi
 	[[ ${DEBUG} ]] && \
 	    printf 1>&2 "%s: location_value=\`%s'\n" \
-		    "${FUNCNAME}" "${location_value}"
+		    "${FUNCNAME[0]}" "${location_value}"
     fi
     printf "%s" "${location_value}"    
 }
@@ -501,6 +512,7 @@ function replace_newline_with_crlf() {
     set -f
     IFS='
 '
+    # shellcheck disable=SC2046
     printf '%s\r\n' $(cat "${inputfile}")  > "${outputfile}"
 }
 
@@ -580,7 +592,7 @@ function parse_roster_item() {
 	roster_line_rest="${roster_line_rest} (0)"
 	if [[ ${DEBUG} ]]; then
 	    printf 1>&2 "\nEXCEPTION in %s: roster_line_rest \`%s' does not contain a roomcapacity; adding \`(0)'.\n" \
-		    "${FUNCNAME}" "${roster_line_rest}"
+		    "${FUNCNAME[0]}" "${roster_line_rest}"
 	fi
     fi
     if [[ "${roster_line_rest}" =~ ${roomcapacity_re} ]]; then
@@ -590,7 +602,7 @@ function parse_roster_item() {
 	if [[ ${DEBUG} ]]; then
 	    ## 4.b do the actual stripping:
 	    printf 1>&2 "%s: roomcapacity_field_value=\`%s', roster_line_rest=\`%s'\n" \
-			"${FUNCNAME}" "${roomcapacity_field_value}" "${roster_line_rest}"
+			"${FUNCNAME[0]}" "${roomcapacity_field_value}" "${roster_line_rest}"
 	fi
     else
 	printf 1>&2 "\n.ANOMALITY: roster_line_rest \`%s' does not contain a roomcapacity.\n" \
@@ -605,7 +617,7 @@ function parse_roster_item() {
 	roster_line_rest="${roster_line_rest%% }"
 	if [[ ${DEBUG} ]]; then
 	    printf 1>&2 "%s: roomnumber_field_value=\`%s', roster_line_rest=\`%s'\n" \
-			"${FUNCNAME}" "${roomnumber_field_value}" "${roster_line_rest}"
+			"${FUNCNAME[0]}" "${roomnumber_field_value}" "${roster_line_rest}"
 	fi
     else
 	printf 1>&2 "\n.ANOMALITY: roster_line_rest \`%s' does not contain a roomnumber.\n" \
@@ -619,11 +631,11 @@ function parse_roster_item() {
 	roster_line_rest="${roster_line_rest// ${teacherabbrev_field_value}/}"
 	if [[ ${DEBUG} ]]; then
 	    printf 1>&2 "%s: teacherabbrev_field_value=\`%s', roster_line_rest=\`%s'\n " \
-			"${FUNCNAME}" "${teacherabbrev_field_value}" "${roster_line_rest}"
+			"${FUNCNAME[0]}" "${teacherabbrev_field_value}" "${roster_line_rest}"
 	fi
     else
 	printf 1>&2 "\n.ANOMALITY in %s: roster_line_rest \`%s' does not contain a teacherabbrev.\n" \
-		    "${FUNCNAME}" "${roster_line_rest}"
+		    "${FUNCNAME[0]}" "${roster_line_rest}"
 	exit 1
     fi
     ## normal match
@@ -656,7 +668,7 @@ function parse_roster_item() {
     vevent+=("UID:${app_name}@${RANDOM}$(date +"%Y%m%d%H%M%S")")
     ## SUMMARY
     vevent+=("SUMMARY:$(ret_vevent_summary \
-    "${course_field_value}" "${teacher_field_value}" "${location_value}" )")
+    "${course_field_value}" )")
     category_value="$(ret_vevent_category "${course_field_value}")"
     vevent+=("CATEGORIES:${category_value}")
     ## add PRIORITY for tests
@@ -686,10 +698,10 @@ function parse_roster_lines_xml() {
     ## where n=${lesson_hour}, essentially skipping the first one,
     ## which contains row headings
     weekday_offset=2
-    weekday_tdselector=$(( ${weekday} + ${weekday_offset} ))
+    weekday_tdselector=$(( weekday + weekday_offset ))
     q_xpath="//tr[1]/following-sibling::*[${lesson_hour}]/*[${weekday_tdselector}]/text()"
     xmllint_args+=(--xpath "${q_xpath}")
-    res="$(${cmd_xmllint} "${xmllint_args[@]}" - <<<"${xml_source}" 2>/dev/null)"
+    res="$(XMLLINT_INDENT=2 ${cmd_xmllint} "${xmllint_args[@]}" - <<<"${xml_source}" 2>/dev/null)"
     if [[ $? -ne 0 ]]; then
 	#printf 1>&2 "\nerror:\n%s\n\n" "${res}"
 	return 1
@@ -713,7 +725,7 @@ function parse_roster_hours() {
 	    while read -r line; do
 		parsed_props="$(parse_roster_item "${week_startdate}" "${weekday}" "${line}")"
 		printf 1>&2 "."
-		printf "${parsed_props}"
+		printf "%s" "${parsed_props}"
 	    done<<<"${res}"
 	done
     done 
@@ -782,7 +794,7 @@ function ret_weekly_timetable_html() {
     if [[ $? -ne 0 ]]; then
 	printf 1>&2 "error in %s\n\tusing data param \`%s' for group_id \`%s' \
 and start_date \`%s'.\n" \
-		    "${FUNCNAME}" "${query_data}" "${group_id}" "${start_date}"
+		    "${FUNCNAME[0]}" "${query_data}" "${group_id}" "${start_date}"
 	return 1
     else
 	printf "%s\n" "${curl_res}"
@@ -808,7 +820,7 @@ function fix_html() {
     res="$(${cmd_tidy} "${tidy_args[@]}" 2>/dev/null <<<"${html_rawsource}")"
     if [[ $? -gt 1 ]]; then
 	printf "%s: error running tidy:\n%s\n" \
-	       "${FUNCNAME}" "${res}"
+	       "${FUNCNAME[0]}" "${res}"
 	return 1
     else
 	printf "%s\n" "${res}"
@@ -825,7 +837,7 @@ function parse_xml() {
     res="$(${cmd_xmllint} "${xmllint_args[@]}" - <<<"${xhtml_clean}" 2>/dev/null)"
     if [[ $? -ne 0 ]]; then
 	printf "%s: error running xmllint:\n%s\n" \
-	       "${FUNCNAME}" "${res}"
+	       "${FUNCNAME[0]}" "${res}"
 	return 1
     else
 	## return the xml
@@ -855,7 +867,6 @@ function ret_untis_date() {
 
 function check_sanity() {
     cmd_xmllint="$(type -p xmllint || return 1)"
-    XMLLINT_INDENT=2
     xmllint_args=(--xmlout)
     xmllint_args+=(--encode "UTF-8")
     xmllint_args+=(--format)
@@ -870,7 +881,7 @@ function check_sanity() {
 	    die "output_path \`${output_path}' already exists and argument --overwrite-output not set.\n"
 	else
 	    printf 1>&2 "NOTICE: argument --overwrite-output is set; overwriting existing ics file \`%s'.\n" \
-			"${${output_path}}"
+			"${output_path}"
 	fi
     fi
     printf 1>&2 "%3s- creating temporary storage directory ... " " "
@@ -895,7 +906,8 @@ function write_ics() {
     ## creates ics file $1 using a temporary file 
     tempfile="$(mktemp "/tmp/${app_name}.XXXX")"
     printf "%s" "${ics_header}" > ${tempfile}
-    printf 1>&2 "%3s- merging weekly ics snippets ...\n"
+    printf 1>&2 "%3s- merging weekly ics snippets ...\n" \
+		" "
     for ics_snippet in ${temp_storage_dir}/*.ics; do
 	vevent_ics="$(<${ics_snippet})"
 	if [[ "${vevent_ics}x" == "x"  ]]; then
@@ -917,6 +929,7 @@ function write_ics() {
 printf 1>&2 ">>> preparing to create ics file from Untis roster\n"
 curdir="$(pwd)"
 declare arg_settings_file arg_roster_url arg_group_name \
+	arg_temp_storage_dir \
 	arg_output_path arg_symlink_path arg_relative_symlink \
 	arg_standard_group_size arg_weeks_ahead \
 	arg_lessonduration_minutes arg_teachers_csv_path arg_courses_csv_path \
@@ -924,7 +937,7 @@ declare arg_settings_file arg_roster_url arg_group_name \
 	arg_ics_organizer_email arg_ics_organizer_cn arg_ics_organizer_sentby_email \
 	arg_people_lookup_url_base arg_ics_organizer_dirurl
 
-declare settings_file roster_url group_name output_path \
+declare roster_url group_name output_path \
 	symlink_path relative_symlink \
 	standard_group_size weeks_ahead lessonduration_minutes \
 	teachers_csv_path courses_csv_path \
@@ -953,7 +966,7 @@ if [[ "${arg_settings_file}x" == "x" ]]; then
     output_path="${arg_output_path:-${curdir}/${group_name}_$(date +'%Y%m%dT%H%M%S').ics}"
     symlink_path="${arg_symlink_path:-}"
     relative_symlink="${arg_relative_symlink:-}"
-    temp_storage_dir="${arg_temp_storagedir}"
+    temp_storage_dir="${arg_temp_storage_dir}"
     standard_group_size="${arg_standard_group_size:-${default_standard_group_size}}"
     weeks_ahead="${arg_weeks_ahead:-${default_weeks_ahead}}"
     lessonduration_minutes="${arg_lessonduration_minutes:-${default_lessonduration_minutes}}"
@@ -992,7 +1005,7 @@ else
 	#roster_url="${roster_url}"
 	#group_name="${group_name}"
 	output_path="${output_path:-${curdir}/${group_name}_$(date +'%Y%m%dT%H%M%S').ics}"
-	temp_storage_dir="${temp_storagedir:-}"
+	temp_storage_dir="${temp_storage_dir:-}"
 	standard_group_size="${standard_group_size:-${default_standard_group_size}}"
 	weeks_ahead="${weeks_ahead:-${default_weeks_ahead}}"
 	lessonduration_minutes="${lessonduration_minutes:-${default_lessonduration_minutes}}"
@@ -1054,15 +1067,14 @@ starting_hours=("08:00"
 		"20:30"
 		"21:15"
 		"22:00")
-untis_dateformat="%m/%d/%Y"
 ics_dt_timeformat="T%H%M%S"
 ## newline seperator for ICS lines
 ics_newline="\n"
 ## max chars per line in ICS files; see wrap_lines function
 ics_maxwidth="73"
-label_unknown="(onbekend)"
 ics_dt_timezoneid="Europe/Amsterdam"
 
+# shellcheck disable=SC1078,SC1079,SC1089
 ics_header="""\
 BEGIN:VCALENDAR
 VERSION:2.0
@@ -1119,14 +1131,15 @@ labels_teachers[-]="(no teacher) mailto:(n/a) dir:(n/a)"
 
 ics_organizer_value="$(wrap_lines "${ics_organizer_value}")"
 
+# shellcheck disable=SC2183
 printf -v rundate_real "%(%Y%m%d)T"
-printf -v rundate_weeknum "%(%V)T" 
 ## current weekday num (monday=1)
+# shellcheck disable=SC2183
 printf -v rundate_weekdaynum "%(%u)T"
 ## substract n days from the current date to get the first day
 ## (monday) of this week, where n is the current day number - 1
 rundate_firstdayofweek="$(date -d \
-"${rundate_real} - $(( ${rundate_weekdaynum} - 1)) day" +"%Y%m%d")"
+"${rundate_real} - $(( rundate_weekdaynum - 1)) day" +"%Y%m%d")"
 
 ## first run
 week_counter=0
